# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.address import Address


class Customer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Customer - a model defined in OpenAPI

        id: The id of this Customer [Optional].
        username: The username of this Customer [Optional].
        address: The address of this Customer [Optional].
    """

    id: Optional[int] = Field(alias="id", default=None)
    username: Optional[str] = Field(alias="username", default=None)
    address: Optional[List[Address]] = Field(alias="address", default=None)

Customer.update_forward_refs()
